travis:
  secure:
    BINSTAR_TOKEN: oXjfRA7hNKBHdcsxht3dP/5xAE0MAQ8q9IC1pVmCERbzOHxwo/Ggv9R5eycIt05JBtHs514DX/acRDAS/35wrC4i2d1Ff02LW7qeU7ACcuYJhfYc2BuZkDHcA8sr9W33WKSsYgzCpu7KkqSnxXjsUxk8z82pbFaHmJuZHrmX8BeJS1XrBsjgKqCTDk/vl6TIGjsmKhebN5fvIDvhkae9U+WVPo/p4UzrcId+fHeRpAYPsqFfm9tN+hqWGLy7KyO63Nyfh4nqF/c3zHG15sI55xUWfKxHpjdAvrTJ443G0N1AeO85fN4u5THGZ/tE4PnttVt4iqZG8kSKrfctSkeArvLJDTGVfL7wSP5W0rUteXaQqcFwmuuCpinSI9Q4Hl7BOMGvY+rA7ZoWXfgxpBFx12XGuMRItPkc8H8utPQW+Z/xRxQqn4uQ8DJwlz6nXfmNRGCTJSN2McY3FYsqEyj2HnQAQWkusNthvYN6Qfp9EHXWW4QeOuoziR9FXN+QOaxq19zm4VHZFxJCbN//iDHBfbZQT/6Nh3qRAfEfmNeIB60oCPbUZ+RHsvY8+wtb/3xnGyC3vT5tUnMN1GDAUjAPwVuvVoxtJ0srYzoSGpG0rE1yEayATVZM6hgp6fP9gOxczbCg30whoMeQEr4WN6R/XAggCMESjJA01JOeFmOzSYI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
